# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  pod 'Flutter'
  pod 'FaceCaptcha', '5.1.0', :source => 'https://github.com/oititec/liveness-ios-specs'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
